name: Run Crypto Tutorial
on: push

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Install Packages
        run: |-
          Rscript -e "install.packages(c('pins','bookdown','tidyverse','DT'))"
      - name: Refresh book
        run: |-
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Refresh entire book from CI automated process" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/bookdown-test.git HEAD:master --force

