name: Run Crypto Tutorial
on: push

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Install Packages
        run: |-
          Rscript -e "install.packages('pins')"
      - name: Refresh book
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::gitbook', clean_envir = FALSE, clean = FALSE)
        shell: Rscript {0}